[package]
name = "include"
version = "0.1.0"
edition = "2021"

build = "build.rs"

[build-dependencies]
testing = { path = "testing", artifact = "bin", target = "x86_64-unknown-none" }
fs_extra = "1.2.0"